# afm2pl
# Autogenerated from man page /usr/share/man/man1/afm2pl.1.gz
complete -c afm2pl -s p --description 'The default is the encoding specified in the afm file, which had better match…'
complete -c afm2pl -s o --description 'Use octal for all character codes in the pl file.'
complete -c afm2pl -s e --description 'Widen or narrow characters by extend_factor.  Default is 1. 0 (natural width).'
complete -c afm2pl -s s --description 'Oblique (slant) characters by slant_factor.  Not recommended either.'
complete -c afm2pl -s f --description 'The value is either the keyword afm2tfm or a comma-separated list of up to fi…'
complete -c afm2pl -s k --description 'Keep original ligatures.'
complete -c afm2pl -s m --description 'Letterspace by letter_spacing/1000 em (integer).'
complete -c afm2pl -s l -s L --description 'See the section on extra ligkern info for details.'
complete -c afm2pl -s n --description 'No prefix.  For . enc- and .'
complete -c afm2pl -s V --description 'Verbose.'
complete -c afm2pl -l help --description 'Display a short usage message.'
complete -c afm2pl -l version --description 'Display the version number of afm2pl.'

