# arlatex
# Autogenerated from man page /usr/share/man/man1/arlatex.1.gz
complete -c arlatex -l version --description 'Output the arlatex script\'s version number.'
complete -c arlatex -l help --description 'Output brief arlatex usage information.'
complete -c arlatex -l document --description 'Specify the master document.'

