# bibdoiadd
# Autogenerated from man page /usr/share/man/man1/bibdoiadd.1.gz
complete -c bibdoiadd -s c --description 'Configuration file.   If this file is absent, some defaults are used.'
complete -c bibdoiadd -s C --description 'Whether to canonize names in the output (1) or not (0).   By default, 1.'
complete -c bibdoiadd -s e --description 'If 1 (default), add empty doi if a doi cannot be found.'
complete -c bibdoiadd -s f --description 'Force checking doi number even if one is present.'

