# bibmradd
# Autogenerated from man page /usr/share/man/man1/bibmradd.1.gz
complete -c bibmradd -s d --description 'Debug mode.'
complete -c bibmradd -s e --description 'If 1 (default), add an empty mrnumber if a mr cannot be found.'
complete -c bibmradd -s f --description 'Force searching for \\s-1MR\\s0 numbers even if the entry already has one.'

