# bibzbladd
# Autogenerated from man page /usr/share/man/man1/bibzbladd.1.gz
complete -c bibzbladd -s d --description 'Debug mode.'
complete -c bibzbladd -s e --description 'If 1 (default), add an empty zblnumber if a zbl cannot be found.'
complete -c bibzbladd -s f --description 'Force searching for Zbl numbers even if the entry already has one.'

