# btrfsck
# Autogenerated from man page /usr/share/man/man8/btrfsck.8.gz
complete -c btrfsck -s b -l backup --description '.'
complete -c btrfsck -l super --description 'if some of the superblocks are damaged.'
complete -c btrfsck -l check-data-csum --description '.'
complete -c btrfsck -l chunk-root --description '.'
complete -c btrfsck -s E -l subvol-extents --description '.'
complete -c btrfsck -s p -l progress --description '.'
complete -c btrfsck -s Q -l qgroup-report --description '.'
complete -c btrfsck -s r -l tree-root --description '.'
complete -c btrfsck -l readonly --description '.'
complete -c btrfsck -s s --description '.'
complete -c btrfsck -l clear-space-cache --description '.'
complete -c btrfsck -l repair --description '.'
complete -c btrfsck -l init-csum-tree --description '.'
complete -c btrfsck -l init-extent-tree --description '.'
complete -c btrfsck -l mode --description '.'
complete -c btrfsck -l force --description '.'

