# c44
# Autogenerated from man page /usr/share/man/man1/c44.1.gz
complete -c c44 -o slice --description 'Specify the number of slices in each chunk.'
complete -c c44 -o size --description 'Specify size targets for each chunk expressed in bytes.'
complete -c c44 -o bpp --description 'Specify size targets for each chunk expressed in bits-per-pixel.'
complete -c c44 -o percent --description 'Specify size targets for each chunk expressed as a percentage of the input fi…'
complete -c c44 -o decibel --description 'Specify quality targets for each chunk expressed as a comma-separated list of…'
complete -c c44 -o dbfrac --description 'Indicate that the decibel values specified in option.'
complete -c c44 -o dpi --description 'Specify the resolution information encoded into the output file expressed in …'
complete -c c44 -o gamma --description 'Specify the gamma correction information encoded into the output file.'
complete -c c44 -o mask --description 'The design of the .'
complete -c c44 -o crcbnormal --description 'Select normal chrominance encoding.'
complete -c c44 -o crcbhalf --description 'Selects half resolution chrominance encoding.'
complete -c c44 -o crcbdelay --description 'This option can be used with .'
complete -c c44 -o crcbfull --description 'Select the highest possible quality for encoding the chrominance information.'
complete -c c44 -o crcbnone --description 'Disable the encoding of the chrominance.'

