# cargo-clean
# Autogenerated from man page /usr/share/man/man1/cargo-clean.1.gz
complete -c cargo-clean -s p -l package --description '.'
complete -c cargo-clean -l doc --description '.'
complete -c cargo-clean -l release --description '.'
complete -c cargo-clean -l target-dir --description '.'
complete -c cargo-clean -l target --description '.'
complete -c cargo-clean -s v -l verbose --description '.'
complete -c cargo-clean -s q -l quiet --description '.'
complete -c cargo-clean -l color --description '.'
complete -c cargo-clean -l manifest-path --description '.'
complete -c cargo-clean -l frozen -l locked --description '.'
complete -c cargo-clean -l offline --description '.'
complete -c cargo-clean -s h -l help --description '.'
complete -c cargo-clean -s Z --description '.'

