# cargo-locate-project
# Autogenerated from man page /usr/share/man/man1/cargo-locate-project.1.gz
complete -c cargo-locate-project -s v -l verbose --description '.'
complete -c cargo-locate-project -s q -l quiet --description '.'
complete -c cargo-locate-project -l color --description '.'
complete -c cargo-locate-project -l manifest-path --description '.'
complete -c cargo-locate-project -s h -l help --description '.'
complete -c cargo-locate-project -s Z --description '.'

