# cargo-pkgid
# Autogenerated from man page /usr/share/man/man1/cargo-pkgid.1.gz
complete -c cargo-pkgid -s p -l package --description '.'
complete -c cargo-pkgid -s v -l verbose --description '.'
complete -c cargo-pkgid -s q -l quiet --description '.'
complete -c cargo-pkgid -l color --description '.'
complete -c cargo-pkgid -l manifest-path --description '.'
complete -c cargo-pkgid -l frozen -l locked --description '.'
complete -c cargo-pkgid -l offline --description '.'
complete -c cargo-pkgid -s h -l help --description '.'
complete -c cargo-pkgid -s Z --description '.'

