# cargo-verify-project
# Autogenerated from man page /usr/share/man/man1/cargo-verify-project.1.gz
complete -c cargo-verify-project -s v -l verbose --description '.'
complete -c cargo-verify-project -s q -l quiet --description '.'
complete -c cargo-verify-project -l color --description '.'
complete -c cargo-verify-project -l manifest-path --description '.'
complete -c cargo-verify-project -l frozen -l locked --description '.'
complete -c cargo-verify-project -l offline --description '.'
complete -c cargo-verify-project -s h -l help --description '.'
complete -c cargo-verify-project -s Z --description '.'

