# cargo-generate-lockfile
# Autogenerated from man page /usr/share/man/man1/cargo-generate-lockfile.1.gz
complete -c cargo-generate-lockfile -s v -l verbose --description '.'
complete -c cargo-generate-lockfile -s q -l quiet --description '.'
complete -c cargo-generate-lockfile -l color --description '.'
complete -c cargo-generate-lockfile -l manifest-path --description '.'
complete -c cargo-generate-lockfile -l frozen -l locked --description '.'
complete -c cargo-generate-lockfile -l offline --description '.'
complete -c cargo-generate-lockfile -s h -l help --description '.'
complete -c cargo-generate-lockfile -s Z --description '.'

