# cargo-yank
# Autogenerated from man page /usr/share/man/man1/cargo-yank.1.gz
complete -c cargo-yank -l vers --description '.'
complete -c cargo-yank -l undo --description '.'
complete -c cargo-yank -l token --description '.'
complete -c cargo-yank -l index --description '.'
complete -c cargo-yank -l registry --description '.'
complete -c cargo-yank -s v -l verbose --description '.'
complete -c cargo-yank -s q -l quiet --description '.'
complete -c cargo-yank -l color --description '.'
complete -c cargo-yank -s h -l help --description '.'
complete -c cargo-yank -s Z --description '.'

