# cargo-login
# Autogenerated from man page /usr/share/man/man1/cargo-login.1.gz
complete -c cargo-login -l registry --description '.'
complete -c cargo-login -s v -l verbose --description '.'
complete -c cargo-login -s q -l quiet --description '.'
complete -c cargo-login -l color --description '.'
complete -c cargo-login -s h -l help --description '.'
complete -c cargo-login -s Z --description '.'

