# cargo-uninstall
# Autogenerated from man page /usr/share/man/man1/cargo-uninstall.1.gz
complete -c cargo-uninstall -l example --description '.'
complete -c cargo-uninstall -l root --description 'oc CARGO_INSTALL_ROOT environment variable oc install.'
complete -c cargo-uninstall -s p -l package --description '.'
complete -c cargo-uninstall -l bin --description '.'
complete -c cargo-uninstall -s v -l verbose --description '.'
complete -c cargo-uninstall -s q -l quiet --description '.'
complete -c cargo-uninstall -l color --description '.'
complete -c cargo-uninstall -s h -l help --description '.'
complete -c cargo-uninstall -s Z --description '.'

