# cargo-new
# Autogenerated from man page /usr/share/man/man1/cargo-new.1.gz
complete -c cargo-new -l bin --description '.'
complete -c cargo-new -l lib --description '.'
complete -c cargo-new -l edition --description '.'
complete -c cargo-new -l name --description '.'
complete -c cargo-new -l vcs --description '.'
complete -c cargo-new -l registry --description '.'
complete -c cargo-new -s v -l verbose --description '.'
complete -c cargo-new -s q -l quiet --description '.'
complete -c cargo-new -l color --description '.'
complete -c cargo-new -s h -l help --description '.'
complete -c cargo-new -s Z --description '.'

