# cargo
# Autogenerated from man page /usr/share/man/man1/cargo.1.gz
complete -c cargo -s V -l version --description '.'
complete -c cargo -l list --description '.'
complete -c cargo -l explain --description '.'
complete -c cargo -s v -l verbose --description '.'
complete -c cargo -s q -l quiet --description '.'
complete -c cargo -l color --description '.'
complete -c cargo -l frozen -l locked --description '.'
complete -c cargo -l offline --description '.'
complete -c cargo -s h -l help --description '.'
complete -c cargo -s Z --description '.'

