# cargo-vendor
# Autogenerated from man page /usr/share/man/man1/cargo-vendor.1.gz
complete -c cargo-vendor -s s -l sync --description '.'
complete -c cargo-vendor -l no-delete --description '.'
complete -c cargo-vendor -l respect-source-config --description '.'
complete -c cargo-vendor -l manifest-path --description '.'
complete -c cargo-vendor -s v -l verbose --description '.'
complete -c cargo-vendor -s q -l quiet --description '.'
complete -c cargo-vendor -l color --description '.'
complete -c cargo-vendor -s h -l help --description '.'
complete -c cargo-vendor -s Z --description '.'
complete -c cargo-vendor -l frozen -l locked --description '.'
complete -c cargo-vendor -l offline --description '.'

