# cargo-update
# Autogenerated from man page /usr/share/man/man1/cargo-update.1.gz
complete -c cargo-update -s p -l package --description '.'
complete -c cargo-update -l aggressive --description '.'
complete -c cargo-update -l precise --description '.'
complete -c cargo-update -l dry-run --description '.'
complete -c cargo-update -s v -l verbose --description '.'
complete -c cargo-update -s q -l quiet --description '.'
complete -c cargo-update -l color --description '.'
complete -c cargo-update -l manifest-path --description '.'
complete -c cargo-update -l frozen -l locked --description '.'
complete -c cargo-update -l offline --description '.'
complete -c cargo-update -s h -l help --description '.'
complete -c cargo-update -s Z --description '.'

