# cargo-metadata
# Autogenerated from man page /usr/share/man/man1/cargo-metadata.1.gz
complete -c cargo-metadata -l no-deps --description '.'
complete -c cargo-metadata -l format-version --description '.'
complete -c cargo-metadata -l features --description '.'
complete -c cargo-metadata -l all-features --description '.'
complete -c cargo-metadata -l no-default-features --description '.'
complete -c cargo-metadata -s v -l verbose --description '.'
complete -c cargo-metadata -s q -l quiet --description '.'
complete -c cargo-metadata -l color --description '.'
complete -c cargo-metadata -l manifest-path --description '.'
complete -c cargo-metadata -l frozen -l locked --description '.'
complete -c cargo-metadata -l offline --description '.'
complete -c cargo-metadata -s h -l help --description '.'
complete -c cargo-metadata -s Z --description '.'

