# cargo-owner
# Autogenerated from man page /usr/share/man/man1/cargo-owner.1.gz
complete -c cargo-owner -s a -l add --description '.'
complete -c cargo-owner -s r -l remove --description '.'
complete -c cargo-owner -s l -l list --description '.'
complete -c cargo-owner -l token --description '.'
complete -c cargo-owner -l index --description '.'
complete -c cargo-owner -l registry --description '.'
complete -c cargo-owner -s v -l verbose --description '.'
complete -c cargo-owner -s q -l quiet --description '.'
complete -c cargo-owner -l color --description '.'
complete -c cargo-owner -s h -l help --description '.'
complete -c cargo-owner -s Z --description '.'

