# cjb2
# Autogenerated from man page /usr/share/man/man1/cjb2.1.gz
complete -c cjb2 -o dpi --description 'Specify the resolution information encoded into the output file expressed in …'
complete -c cjb2 -o lossless --description 'Ensure that the encoded image is pixel-per-pixel equal to the initial image.'
complete -c cjb2 -o clean --description 'Only remove flyspecks from the input image.'
complete -c cjb2 -o lossy --description 'Substitute patterns with small variations.'
complete -c cjb2 -o losslevel --description 'Specify the aggressiveness of the lossy compression.'
complete -c cjb2 -o verbose --description 'Display informational messages while running.'

