# cpaldjvu
# Autogenerated from man page /usr/share/man/man1/cpaldjvu.1.gz
complete -c cpaldjvu -o dpi --description 'Specify the resolution information encoded into the output file expressed in …'
complete -c cpaldjvu -o colors --description 'Specify a maximum number of distinct colors for the color quantization algori…'
complete -c cpaldjvu -o bgwhite --description 'Cause the background layer to use the lightest quantified color instead of th…'
complete -c cpaldjvu -o verbose --description 'Display informational messages while running.'

