# csepdjvu
# Autogenerated from man page /usr/share/man/man1/csepdjvu.1.gz
complete -c csepdjvu -s d --description 'Specify the resolution information encoded into the output file expressed in …'
complete -c csepdjvu -s q --description 'Specify the encoding quality of the IW44 encoded background layer.'
complete -c csepdjvu -s t --description 'Program   csepdjvu interprets certain comments in the separated file to const…'
complete -c csepdjvu -s v --description 'Display a brief message describing each page.'
complete -c csepdjvu -o slice --description 'of program c44 .'
complete -c csepdjvu -o vv --description 'Display extensive informational messages during encoding.'

