# csscombine
# Autogenerated from man page /usr/share/man/man1/csscombine.1.gz
complete -c csscombine -s h -l help --description 'Show help message and exit.'
complete -c csscombine -s m -l minify --description 'Saves minified version of combined files, default is false.'
complete -c csscombine -s s -l sourceencoding --description 'Encoding of input, defaulting to "css".'
complete -c csscombine -s t -l targetencoding --description 'Encoding of output, defaulting to "UTF-8".'
complete -c csscombine -s u -l url --description 'URL to parse, path.  is ignored if URL is given.'

