# csscapture
# Autogenerated from man page /usr/share/man/man1/csscapture.1.gz
complete -c csscapture -s d -l debug --description 'Show debug messages during capturing.'
complete -c csscapture -s h -l help --description 'Show help message and exit.'
complete -c csscapture -s m -l minified --description 'Saves minified version of captured files.'
complete -c csscapture -s n -l notsave --description 'If given, files are NOT saved, only log is written.'
complete -c csscapture -s s -l saveto --description 'Save retrieved files to DIR, defaults to . /_CSSCapture_SAVED.'
complete -c csscapture -s u -l useragent --description 'Useragent to use for request of URL, default is urllib2s default.'

