# cssparse_py2
# Autogenerated from man page /usr/share/man/man1/cssparse_py2.1.gz
complete -c cssparse_py2 -s d -l debug --description 'Activate debugging output.'
complete -c cssparse_py2 -s e -l encoding --description 'Encoding of the file or override encoding found.'
complete -c cssparse_py2 -s h -l help --description 'Display help message and exit.'
complete -c cssparse_py2 -s m -l minify --description 'Minify parsed CSS.'
complete -c cssparse_py2 -s s -l string --description 'Parse given string.'
complete -c cssparse_py2 -s u -l url --description 'Parse the given URL.'

