# cssparse
# Autogenerated from man page /usr/share/man/man1/cssparse.1.gz
complete -c cssparse -s d -l debug --description 'Activate debugging output.'
complete -c cssparse -s e -l encoding --description 'Encoding of the file or override encoding found.'
complete -c cssparse -s h -l help --description 'Display help message and exit.'
complete -c cssparse -s m -l minify --description 'Minify parsed CSS.'
complete -c cssparse -s s -l string --description 'Parse given string.'
complete -c cssparse -s u -l url --description 'Parse the given URL.'

