# ctanify
# Autogenerated from man page /usr/share/man/man1/ctanify.1.gz
complete -c ctanify -s h -l help --description 'Output basic usage information and exit.'
complete -c ctanify -s V -l version --description 'Output ctanify\'s version number and exit.'
complete -c ctanify -s p -l pkgname --description 'Specify explicitly a package name.'
complete -c ctanify -l noauto --description 'Do not automatically add files to the tarball.'

