# cweb
# Autogenerated from man page /usr/share/man/man1/cweb.1.gz
complete -c cweb -s b --description 'option suppresses the banner line that normally appears on your terminal when…'
complete -c cweb -s h --description 'option suppresses the happy message that normally appears if the processing w…'
complete -c cweb -s p --description 'option suppresses progress reports (starred module numbers) as the processing…'
complete -c cweb -o bhp --description 'you get nothing but error messages.'
complete -c cweb -s f --description 'means do not force a newline after every statement in the formatted output.'
complete -c cweb -s e --description 'inhibits the enclosure of C material formatted by cweave in brackets \\PB{. }.'
complete -c cweb -s x --description 'means omit the index and table of contents.'

