# dconf-editor
# Autogenerated from man page /usr/share/man/man1/dconf-editor.1.gz
complete -c dconf-editor -s h -l help --description 'Prints the command-line options and exits.'
complete -c dconf-editor -s v -l version --description 'Prints the release version and exits.'
complete -c dconf-editor -l list-relocatable-schemas --description 'Prints the list of relocatable schemas and exits.'

