# dh_installdirs
# Autogenerated from man page /usr/share/man/man1/dh_installdirs.1.gz
complete -c dh_installdirs -s A -l all --description 'Create any directories specified by command line parameters in \\s-1ALL\\s0 pac…'

