# djvmcvt
# Autogenerated from man page /usr/share/man/man1/djvmcvt.1.gz
complete -c djvmcvt -s b --description 'Create a bundled multi-page DjVu document named R docout. djvu .'
complete -c djvmcvt -s i --description 'Create an indirect multi-page DjVu document.'

