# djvutxt
# Autogenerated from man page /usr/share/man/man1/djvutxt.1.gz
complete -c djvutxt -l page --description 'Specify which pages should be processed.'
complete -c djvutxt -l detail --description 'This options causes  djvutxt to output S-expressions  specifying the position…'
complete -c djvutxt -o detail --description 'and.'
complete -c djvutxt -o escape --description 'this program simply outputs the UTF-8 text.  Option.'
complete -c djvutxt -l escape --description 'Output escape sequences of the form  "ooo" for all non ASCII or non printable…'

