# djvutoxml
# Autogenerated from man page /usr/share/man/man1/djvutoxml.1.gz
complete -c djvutoxml -l page --description 'Select a page in a multi-page document.'
complete -c djvutoxml -l with-text --description 'Specifies the  HIDDENTEXT  element for each page should be included in the ou…'
complete -c djvutoxml -l with-anno --description 'flag then the.'
complete -c djvutoxml -l without-anno --description 'is implied.   If none of the  .'
complete -c djvutoxml -l without-text --description '.'
complete -c djvutoxml -s o --description 'In principle the target DjVu file is the file  referenced by the OBJECT  elem…'

