# dropbox
# Autogenerated from man page /usr/share/man/man1/dropbox.1.gz
complete -c dropbox -s i -l install --description 'dropbox filestatus [-l] [-a] [FILE].'
complete -c dropbox -s l -l list --description '.'
complete -c dropbox -s a -l all --description 'Aliases: stat dropbox proxy MODE [TYPE] [HOST] [PORT] [USERNAME] [PASSWORD].'

