# ebb
# Autogenerated from man page /usr/share/man/man1/ebb.1.gz
complete -c ebb -s v --description 'Be verbose.'
complete -c ebb -s q --description 'Be quiet.'
complete -c ebb -s O --description 'Write output to standard output.'
complete -c ebb -s m --description 'Write output in dvipdfm\'s ``bb\'\' format.'

