# epiphany-browser
# Autogenerated from man page /usr/share/man/man1/epiphany-browser.1.gz
complete -c epiphany-browser -s '?' -l help --description 'Show help options . PP Application options.'
complete -c epiphany-browser -s n -l new-tab --description 'Open a new tab in an existing browser window.'
complete -c epiphany-browser -l new-window --description 'Open a new browser window.'
complete -c epiphany-browser -l import-bookmarks --description 'Import bookmarks from the given file.'
complete -c epiphany-browser -s l -l load-session --description 'Load the given session file.'
complete -c epiphany-browser -s t -l add-bookmark --description 'Add a bookmark.'
complete -c epiphany-browser -s p -l private-instance --description 'Start a private instance (temporary profile directory, not private browsing m…'
complete -c epiphany-browser -l incognito-mode --description 'Start a private instance in incognito mode.'
complete -c epiphany-browser -l profile --description 'Profile directory to use in the private instance.'
complete -c epiphany-browser -l version --description 'Show version.'

