# exonpairs
# Autogenerated from man page /usr/share/man/man1/exonpairs.1.gz
complete -c exonpairs -o min-intron --description 'minimum Intron length [30].'
complete -c exonpairs -o max-intron --description 'maximum Intron length [10000].'
complete -c exonpairs -o einit-length --description 'minimum Einit length in bp [10].'
complete -c exonpairs -o eterm-length --description 'minimum Eterm length in bp [10].'
complete -c exonpairs -o exon-length --description 'minimum Exon length in bp [30] .'
complete -c exonpairs -o einit-score --description 'minimum Einit score in bits [-5].'
complete -c exonpairs -o eterm-score --description 'minimum Eterm score in bits [-5].'
complete -c exonpairs -o exon-score --description 'minimum Exon score in bits [-5].'
complete -c exonpairs -o pair-score --description 'minimum pair score (exon-intron-exon) [10].'
complete -c exonpairs -o flank-length --description 'length of flanking sequence per exon [20].'
complete -c exonpairs -o intron-score --description '.'
complete -c exonpairs -o lcmask --description 'treat lowercase as N.'

