# fasd
# Autogenerated from man page /usr/local/man/man1/fasd.1
complete -c fasd -s s --description '.'
complete -c fasd -s l --description '.'
complete -c fasd -s i --description '.'
complete -c fasd -s e --description '.'
complete -c fasd -s b --description '.'
complete -c fasd -s B --description '.'
complete -c fasd -s a --description '.'
complete -c fasd -s d --description '.'
complete -c fasd -s f --description '.'
complete -c fasd -s r --description '.'
complete -c fasd -s t --description '.'
complete -c fasd -s R --description '.'
complete -c fasd -s h --description '.'

