# fathom
# Autogenerated from man page /usr/share/man/man1/fathom.1.gz
complete -c fathom -o help --description 'report useful information.'
complete -c fathom -o validate --description '.'
complete -c fathom -o gene-stats -o errors-ok -o nucleotide -o dinucleotide --description '.'
complete -c fathom -o categorize --description '.'
complete -c fathom -o export -o plus --description '.'
complete -c fathom -o extract -o length -o offset --description '.'
complete -c fathom -o exon-intron --description '.'
complete -c fathom -o split -o training -o GC -o repeat --description '.'
complete -c fathom -o ace-format -o dna -o extra --description '.'
complete -c fathom -o compare-genes --description '.'
complete -c fathom -o score-genes --description '.'
complete -c fathom -o filter-genes -o min-score -o min-length --description '.'

