# forge
# Autogenerated from man page /usr/share/man/man1/forge.1.gz
complete -c forge -o pseudocount --description '[1]   (absolute number for all models) . HP -pseudoCoding <float> [0. 0] (eg.'
complete -c forge -o pseudoInter --description '[0. 0].'
complete -c forge -o min-counts --description '[0] . HP -lcmask [-fragmentN].'
complete -c forge -o utr5-length --description '[50].'
complete -c forge -o utr5-offset --description '[10].'
complete -c forge -o utr3-length --description '[50].'
complete -c forge -o utr3-offset --description '[10].'
complete -c forge -o explicit --description '[250].'
complete -c forge -o min-intron --description '[30].'
complete -c forge -o help --description '.'
complete -c forge -o verbose --description '.'
complete -c forge -o pseudoCoding --description '.'
complete -c forge -o pseudoIntron --description '.'
complete -c forge -o lcmask --description '.'
complete -c forge -o boost --description '(file of ID <int>).'

