# fzf-tmux
# Autogenerated from man page /home/ryan/.fzf/man/man1/fzf-tmux.1
complete -c fzf-tmux -s u --description 'Split above (up).'
complete -c fzf-tmux -s d --description 'Split below (down).'
complete -c fzf-tmux -s l --description 'Split left.'
complete -c fzf-tmux -s r --description 'Split right.'

