# gdbserver
# Autogenerated from man page /usr/share/man/man1/gdbserver.1.gz
complete -c gdbserver -l help --description 'List all options, with brief explanations.'
complete -c gdbserver -l version --description 'This option causes gdbserver to print its version number and exit.'
complete -c gdbserver -l attach --description 'gdbserver will attach to a running program.   The syntax is: . Sp .'
complete -c gdbserver -l multi --description 'To start \\f(CW\\*(C`gdbserver\\*(C\' without supplying an initial command to run…'
complete -c gdbserver -l debug --description 'Instruct \\f(CW\\*(C`gdbserver\\*(C\' to display extra status information about t…'
complete -c gdbserver -l remote-debug --description 'Instruct \\f(CW\\*(C`gdbserver\\*(C\' to display remote protocol debug output.'
complete -c gdbserver -l debug-format --description 'Instruct \\f(CW\\*(C`gdbserver\\*(C\' to include extra information in each line o…'
complete -c gdbserver -l wrapper --description 'Specify a wrapper to launch programs for debugging.'

