# gmessage
# Autogenerated from man page /usr/share/man/man1/gmessage.1.gz
complete -c gmessage -o bg --description 'br Sets the background color of the message to COLOR.'
complete -c gmessage -o buttons --description 'br Defines the buttons to be created.'
complete -c gmessage -o center --description 'br Opens the gxmessage window in the middle of the screen.'
complete -c gmessage -o default --description 'br Opens the gxmessage window with input focused on the specified button.'
complete -c gmessage -o display --description 'br Specifies the X display to use.'
complete -c gmessage -o fg --description 'br Sets the message text color to COLOR.'
complete -c gmessage -o file --description 'br Causes the named file to be used as the message source.'
complete -c gmessage -o fn -o font --description 'br Specifies the message font, using GTK\'s font specification system.'
complete -c gmessage -o geometry --description 'br Sets the window\'s size and/or position.  Examples: .'
complete -c gmessage -o help --description 'br Displays basic usage information then exits.'
complete -c gmessage -o iconic --description 'br Opens the gxmessage window in its iconized (minimized) state.'
complete -c gmessage -o name --description 'br Sets the gxmessage window\'s name to NAME.'
complete -c gmessage -o nearmouse --description 'br Opens the gxmessage window near the mouse pointer.'
complete -c gmessage -o print --description 'br Writes the LABEL of the selected button to stdout.'
complete -c gmessage -o timeout --description 'br Automatically closes the gxmessage window with an exit code of 0 if no but…'

