# gpg-wks-server
# Autogenerated from man page /usr/share/man/man1/gpg-wks-server.1.gz
complete -c gpg-wks-server -s v -l verbose --description 'Enable verbose output.'
complete -c gpg-wks-server -s q -l quiet --description 'Be somewhat more quiet.'
complete -c gpg-wks-server -l send --description 'Send the mail using sendmail.'
complete -c gpg-wks-server -s o -l output --description 'Write the mail to FILE.'
complete -c gpg-wks-server -l from --description 'Use ADDR as the default sender.'
complete -c gpg-wks-server -l header --description 'Add "NAME: VALUE" as header to all mails.'
complete -c gpg-wks-server -l debug --description 'Set  debugging  flags.'
complete -c gpg-wks-server -l receive --description 'command.'
complete -c gpg-wks-server -l cron --description 'Run regular jobs.'
complete -c gpg-wks-server -l list-domains --description 'List configured domains, and checks some file and directory permissions.'
complete -c gpg-wks-server -l version --description 'Show program version and some meta information.'
complete -c gpg-wks-server -s h -l help --description 'Output a short usage information.'
complete -c gpg-wks-server -l warranty --description 'Print warranty information.'
complete -c gpg-wks-server -l dump-options --description 'Dump all available options and commands.'
complete -c gpg-wks-server -l gpg --description 'Use the specified command instead of gpg .'

