# hmm-info
# Autogenerated from man page /usr/share/man/man1/hmm-info.1.gz
complete -c hmm-info -o models --description '.'
complete -c hmm-info -o general --description '.'
complete -c hmm-info -o durations --description '.'

