# ibus-engine-m17n
# Autogenerated from man page /usr/share/man/man1/ibus-engine-m17n.1.gz
complete -c ibus-engine-m17n -s h -l help --description 'show this message.'
complete -c ibus-engine-m17n -s d -l daemonize --description 'daemonize ibus engine.'
complete -c ibus-engine-m17n -s l -l list --description 'list all m17n input methods.'
complete -c ibus-engine-m17n -s a -l all --description 'enable all m17n input methods example: . /ibus-engine-m17n zh:py ja:trycode.'

