# img2txt
# Autogenerated from man page /usr/share/man/man1/img2txt.1.gz
complete -c img2txt -s W -l width --description 'Change output column count.  If not given, the default is set to 60.'
complete -c img2txt -s H -l height --description 'Change output line count.'
complete -c img2txt -s x -l font-width --description 'Change output font width.  If not given, the default is set to 6.'
complete -c img2txt -s y -l font-height --description 'Change output font height.  If not given, the default is set to 10.'
complete -c img2txt -s b -l brightness --description 'Change image brightness.  Default to 1. 0.'
complete -c img2txt -s c -l contrast --description 'Change image contrast.  Default to 1. 0.'
complete -c img2txt -s g -l gamma --description 'Change image gamma.  Default to 1. 0.'
complete -c img2txt -s d -l dither --description 'Change dithering algorithm.'
complete -c img2txt -s f -l format --description 'Change output format.'
complete -c img2txt -s h -l help --description 'Display help message and exit.'
complete -c img2txt -s v -l version --description 'Display version of the program and exit.'

