# io
# Autogenerated from man page /usr/share/man/man1/io.elementary.terminal.1.gz
complete -c io -s e -l execute --description 'Execute the specified binary with given parameters in terminal.'
complete -c io -s w -l working-directory --description 'Set the specified directory as shell working directory on startup AUTHOR Pant…'

