# ippserver
# Autogenerated from man page /usr/share/man/man1/ippserver.1.gz
complete -c ippserver -s 2 --description 'Report support for two-sided (duplex) printing.'
complete -c ippserver -s M --description 'Set the manufacturer of the printer.  The default is "Test".'
complete -c ippserver -s P --description 'Report support for PIN printing.'
complete -c ippserver -s c --description 'Run the specified command for each document that is printed.'
complete -c ippserver -s d --description 'Specifies the directory that will hold the print files.'
complete -c ippserver -s f --description 'Specifies a list of MIME media types that the server will accept.'
complete -c ippserver -s h --description 'Shows program help.'
complete -c ippserver -s i --description 'Specifies the printer icon file for the server.  The default is "printer.'
complete -c ippserver -s k --description 'Keeps the print documents in the spool directory rather than deleting them.'
complete -c ippserver -s l --description 'Specifies the human-readable location string that is reported by the server.'
complete -c ippserver -s m --description 'Specifies the model name of the printer.  The default is "Printer".'
complete -c ippserver -s n --description 'Specifies the hostname that is reported by the server.'
complete -c ippserver -s p --description 'Specifies the port number to listen on.'
complete -c ippserver -s r --description 'Specifies the Bonjour subtype(s) to advertise.'
complete -c ippserver -s s --description 'Specifies the printer speed in pages per minute.'
complete -c ippserver -s v --description 'Be (very) verbose when logging activity to the standard output.'

