# jsc
# Autogenerated from man page /usr/share/man/man1/jsc.1.gz
complete -c jsc -s e --description 'Evaluate argument as script code.'
complete -c jsc -s f --description 'Specifies a source file (deprecated).'
complete -c jsc -s h -l help --description 'Shows summary of command-line options.'
complete -c jsc -s i --description 'Enables interactive mode (default if no files are specified).'
complete -c jsc -s p --description 'Outputs profiling data to a file.'
complete -c jsc -s s --description 'Installs signal handlers that exit on a crash.'
complete -c jsc -s x --description 'Output exit code before terminating.'
complete -c jsc -l options --description 'Dumps all JSC VM options and exits.'
complete -c jsc -l dumpOptions --description 'Dumps all JSC VM options before continuing.'
complete -c jsc -l '<jsc' --description 'Sets the specified JSC VM option.'

