# latex2man
# Autogenerated from man page /usr/share/man/man1/latex2man.1.gz
complete -c latex2man -o ttransfile --description 'Translation for user defined LaTeX macros.'
complete -c latex2man -o cCSSfile --description 'If you use the -H you can also specify a file that contains CSS  style sheets.'
complete -c latex2man -s M --description 'Produce output suitable for the man(1) command (default).'
complete -c latex2man -s H --description 'Instead of producing output suitable for the man(1) command, HTML code is pro…'
complete -c latex2man -s T --description 'Instead of producing output suitable for the man(1) command, TexInfo code is …'
complete -c latex2man -s L --description 'The LaTeX source is written to the outfile.'
complete -c latex2man -o Cname --description 'Output the conditional text for name.'
complete -c latex2man -o achar --description 'Is used only in conjunction with -T. br Background: .'
complete -c latex2man -s h --description 'Show a help text.'
complete -c latex2man -s a --description 'supresses the indentation of a line.'
complete -c latex2man -s V --description ' Show version information.'
complete -c latex2man -o 'C\'abc' --description 'and have a look to the generated output.'
complete -c latex2man -o CHTML --description ' the lines 1a, 2b, 3b, and 4b; .'
complete -c latex2man -o CTEXI --description ' the lines 1b, 2a, 3b, and 4b; .'
complete -c latex2man -o CMAN --description ' the lines 1b, 2b, 3a, and 4b; .'
complete -c latex2man -o CLATEX --description ' the lines 1b, 2b, 3b, and 4a; .'

