# latex-git-log
# Autogenerated from man page /usr/share/man/man1/latex-git-log.1.gz
complete -c latex-git-log -l width --description 'Set the width in cm of the commit message field in the LaTeX table.'
complete -c latex-git-log -l git-c-add --description 'Set an base \\s-1URL\\s0 to link to a commit.'

