# light-locker
# Autogenerated from man page /usr/share/man/man1/light-locker.1.gz
complete -c light-locker -l debug --description 'Enable debugging code.'
complete -c light-locker -l lock-after-screensaver --description 'Lock the screen S seconds after the screensaver started.'
complete -c light-locker -l late-locking --description 'Lock the screen on screensaver deactivation.'
complete -c light-locker -l no-late-locking --description 'Lock the screen on screensaver activation.'
complete -c light-locker -l lock-on-suspend --description 'Lock the screen on suspend/resume.'
complete -c light-locker -l no-lock-on-suspend --description 'Do not lock the screen on suspend/resume.'
complete -c light-locker -l lock-on-lid --description 'Lock the screen on lid close.'
complete -c light-locker -l no-lock-on-lid --description 'Do not lock the screen on lid close.'
complete -c light-locker -l idle-hint --description 'Set the session idle hint while the screenaver is active.'
complete -c light-locker -l no-idle-hint --description 'Don\'t set the idle hint.  Let something else handle that.'

