# light-locker-command
# Autogenerated from man page /usr/share/man/man1/light-locker-command.1.gz
complete -c light-locker-command -s q -l query --description 'Query the state of the locker.'
complete -c light-locker-command -s t -l time --description 'Query the length of time the locker has been active.'
complete -c light-locker-command -s l -l lock --description 'Tells the running locker process to lock the screen immediately.'
complete -c light-locker-command -s a -l activate --description 'Turn the screensaver on (blank the screen).'
complete -c light-locker-command -s d -l deactivate --description 'If the screensaver is active then deactivate it (un-blank the screen).'
complete -c light-locker-command -s p -l poke --description 'Poke the running locker to simulate user activity.'
complete -c light-locker-command -s i -l inhibit --description 'Inhibit the screensaver from activating.'
complete -c light-locker-command -s n -l application-name --description 'The calling application that is inhibiting the screensaver.'
complete -c light-locker-command -s r -l reason --description 'The reason for inhibiting the screensaver.'
complete -c light-locker-command -s V -l version --description 'Version of this application SEE ALSO light-locker (1).'

