# ltx2crossrefxml
# Autogenerated from man page /usr/share/man/man1/ltx2crossrefxml.1.gz
complete -c ltx2crossrefxml -s c --description 'Configuration file.   If this file is absent, some defaults are used.'

