# makeglossaries-lite
# Autogenerated from man page /usr/share/man/man1/makeglossaries-lite.1.gz
complete -c makeglossaries-lite -s q --description 'Quiet mode.  Reduces chatter to standard output.'
complete -c makeglossaries-lite -s n --description 'Print the commands that would normally be executed but don\'t run them.'
complete -c makeglossaries-lite -s o --description 'Use file as the output file.'
complete -c makeglossaries-lite -s s --description 'Use file as the style file.'
complete -c makeglossaries-lite -s t --description 'Use file as the transcript file.'
complete -c makeglossaries-lite -s l --description 'Letter ordering.'
complete -c makeglossaries-lite -s L --description 'This option only has an effect if xindy is called.  Sets the language.'
complete -c makeglossaries-lite -s c --description 'Compress intermediate blanks (makeindex only).'
complete -c makeglossaries-lite -s g --description 'Employ German word ordering (makeindex only).'
complete -c makeglossaries-lite -s p --description 'Sets the starting page number to be num (makeindex only).'
complete -c makeglossaries-lite -s r --description 'Disable implicit page range formation (makeindex only).'
complete -c makeglossaries-lite -s m --description 'Specify the full path name for makeindex to file in the  event that makeindex…'
complete -c makeglossaries-lite -s x --description 'Specify the full path name for xindy to file in the  event that xindy isn\'t o…'
complete -c makeglossaries-lite -l version --description 'Prints version number and exits.'

