# markdown
# Autogenerated from man page /usr/share/man/man1/markdown.1.gz
complete -c markdown -l html4tags --description 'Use \\s-1HTML 4\\s0 style for empty element tags, e. g. : . Sp . Vb 1     <br> .'
complete -c markdown -s v -l version --description 'Display Markdown\'s version number and copyright information.'

