# markdown_py
# Autogenerated from man page /usr/share/man/man1/markdown_py.1.gz
complete -c markdown_py -l version --description 'Show program\'s version number and exit.'
complete -c markdown_py -s h -l help --description 'Show the help message and exit.'
complete -c markdown_py -s f -l file --description 'Write output to OUTPUT_FILE.  Defaults to STDOUT.'
complete -c markdown_py -s e -l encoding --description 'Encoding for input and output files.'
complete -c markdown_py -s s -l safe --description 'Deprecated! \'replace\', \'remove\' or \'escape\' HTML tags in input.'
complete -c markdown_py -s o -l output_format --description '\'xhtml1\' (default), \'html4\' or \'html5\'.'
complete -c markdown_py -s n -l no_lazy_ol --description 'Observe number of first item of ordered lists.'
complete -c markdown_py -s x -l extension --description 'Load extension EXTENSION.'
complete -c markdown_py -s c -l extension_configs --description 'Read extension configurations from CONFIG_FILE.'
complete -c markdown_py -s q -l quiet --description 'Suppress all warnings.'
complete -c markdown_py -s v -l verbose --description 'Print all warnings.'
complete -c markdown_py -l noisy --description 'Print debug messages.'

