# mkjobtexmf
# Autogenerated from man page /usr/share/man/man1/mkjobtexmf.1.gz
complete -c mkjobtexmf -l jobname --description 'It is the name of the job.  `<jobname>.'
complete -c mkjobtexmf -l texname --description 'The name of the TeX input file, if it differs from <jobname>. tex.'
complete -c mkjobtexmf -l texopt --description 'Additional option for the TeX compiler, examples are \\f(CW\\*(C`--ini\\*(C\' or …'
complete -c mkjobtexmf -l destdir --description 'Specifies the name of the destination directory where the result is collected.'
complete -c mkjobtexmf -l output --description 'Also add output files.'
complete -c mkjobtexmf -l strace --description 'Use method with program strace, see \\*(L"\\s-1DESCRIPTION\\s0\\*(R".'
complete -c mkjobtexmf -l copy --description 'Files are copied instead of creating symbolic links.'
complete -c mkjobtexmf -l flat --description 'Files are linked or copied without path elements.'
complete -c mkjobtexmf -l exclude-ext --description 'Files with extension <ext> are excluded.'
complete -c mkjobtexmf -l cmd-tex --description 'Command for the TeX compiler.  Default is pdflatex.'
complete -c mkjobtexmf -l cmd-kpsewhich --description 'Command for kpsewhich.'
complete -c mkjobtexmf -l cmd-texhash --description 'Command for updating the file name database of the generated texmf tree.'
complete -c mkjobtexmf -l cmd-strace --description 'Command for strace.'
complete -c mkjobtexmf -l verbose --description 'Verbose messages.'
complete -c mkjobtexmf -l help --description 'Display help screen.'

