# mmafm
# Autogenerated from man page /usr/share/man/man1/mmafm.1.gz
complete -c mmafm -l output -s o --description 'Send output to  file instead of standard output.  \'.'
complete -c mmafm -l weight -s w --description 'Set the weight axis to  R N .  \'.'
complete -c mmafm -l width -s W --description 'Set the width axis to  R N .  \'.'
complete -c mmafm -l optical-size -s O --description 'Set the optical size axis to  R N .  \'.'
complete -c mmafm -l style --description 'Set the style axis to  R N .'
complete -c mmafm -l 1 -l 2 -l 3 -l 4 --description 'Set the first (second, third, fourth) axis to R N .  \'.'
complete -c mmafm -l precision -s p --description 'Round output numbers so they have at most  N digits after the decimal point.'

