# mtx-cache
# Autogenerated from man page /usr/share/man/man1/mtx-cache.1.gz
complete -c mtx-cache -l purge --description 'remove not used files.'
complete -c mtx-cache -l erase --description 'completely remove cache.'
complete -c mtx-cache -l list --description 'show cache.'
complete -c mtx-cache -l fonts --description 'only wipe fonts AUTHOR More information about ConTeXt and the tools that come…'

