# mtx-tools
# Autogenerated from man page /usr/share/man/man1/mtx-tools.1.gz
complete -c mtx-tools -l disarmutfbomb --description 'remove utf bomb if present.'
complete -c mtx-tools -l force --description 'remove indeed.'
complete -c mtx-tools -l dirtoxml --description 'glob directory into xml.'
complete -c mtx-tools -l pattern --description 'glob pattern (default: *).'
complete -c mtx-tools -l url --description 'url attribute (no processing).'
complete -c mtx-tools -l root --description 'the root of the globbed path (default: . ).'
complete -c mtx-tools -l output --description 'output filename (console by default).'
complete -c mtx-tools -l recurse --description 'recurse into subdirecories.'
complete -c mtx-tools -l stripname --description 'take pathpart of given pattern.'
complete -c mtx-tools -l longname --description 'set name attributes to full path name.'
complete -c mtx-tools -l downcase --description 'lowercase names.'

