# mtx-babel
# Autogenerated from man page /usr/share/man/man1/mtx-babel.1.gz
complete -c mtx-babel -l language --description 'conversion language (e. g.  greek).'
complete -c mtx-babel -l structure --description 'obey given structure (e. g.  \'document\', default: \'context\').'
complete -c mtx-babel -l convert --description 'convert babel codes into utf AUTHOR More information about ConTeXt and the to…'

