# mtx-interface
# Autogenerated from man page /usr/share/man/man1/mtx-interface.1.gz
complete -c mtx-interface -l interfaces --description 'generate context mkii interface files.'
complete -c mtx-interface -l context --description 'equals --interfaces --messages --languages.'
complete -c mtx-interface -l scite --description 'generate scite interface.'
complete -c mtx-interface -l bbedit --description 'generate bbedit interface files.'
complete -c mtx-interface -l jedit --description 'generate jedit interface files.'
complete -c mtx-interface -l textpad --description 'generate textpad interface files.'
complete -c mtx-interface -l text --description 'create text files for commands and environments.'
complete -c mtx-interface -l raw --description 'report commands to the console.'
complete -c mtx-interface -l check --description 'generate check file.'
complete -c mtx-interface -l toutf --description 'replace named characters by utf.'
complete -c mtx-interface -l preprocess --description 'preprocess mkvi files to tex files [force,suffix].'
complete -c mtx-interface -l suffix --description 'use given suffix for output files.'
complete -c mtx-interface -l force --description 'force action even when in doubt AUTHOR More information about ConTeXt and the…'

