# mtx-modules
# Autogenerated from man page /usr/share/man/man1/mtx-modules.1.gz
complete -c mtx-modules -l convert --description 'convert source files (tex, mkii, mkiv, mp) to \'ted\' files.'
complete -c mtx-modules -l process --description 'process source files (tex, mkii, mkiv, mp) to \'pdf\' files.'
complete -c mtx-modules -l prep --description 'use original name with suffix \'prep\' appended AUTHOR More information about C…'

