# mtx-patterns
# Autogenerated from man page /usr/share/man/man1/mtx-patterns.1.gz
complete -c mtx-patterns -l convert --description 'generate context language files (mnemonic driven, if not given then all).'
complete -c mtx-patterns -l check --description 'check pattern file (or those used by context when no file given).'
complete -c mtx-patterns -l path --description 'source path where hyph-foo. tex files are stored.'
complete -c mtx-patterns -l destination --description 'destination path.'
complete -c mtx-patterns -l specification --description 'additional patterns: e. g. : =cy,hyph-cy,welsh.'
complete -c mtx-patterns -l compress --description 'compress data.'
complete -c mtx-patterns -l words --description 'update words in given file.'
complete -c mtx-patterns -l hyphenate --description 'show hypephenated words AUTHOR More information about ConTeXt and the tools t…'

