# mtx-fcd
# Autogenerated from man page /usr/share/man/man1/mtx-fcd.1.gz
complete -c mtx-fcd -l clear --description 'clear the cache.'
complete -c mtx-fcd -l scan --description 'clear the cache and add given path(s).'
complete -c mtx-fcd -l add --description 'add given path(s).'
complete -c mtx-fcd -l find --description 'find given path (can be substring).'
complete -c mtx-fcd -l stub --description 'print platform stub file.'
complete -c mtx-fcd -l list --description 'show roots of cached dirs.'
complete -c mtx-fcd -l history --description '.'
complete -c mtx-fcd -l nohistory --description '.'
complete -c mtx-fcd -l help --description 'show this help AUTHOR More information about ConTeXt and the tools that come …'

