# mtx-profile
# Autogenerated from man page /usr/share/man/man1/mtx-profile.1.gz
complete -c mtx-profile -l analyze --description 'analyze lua calls.'
complete -c mtx-profile -l trace --description 'analyze tex calls AUTHOR More information about ConTeXt and the tools that co…'

