# mtx-scite
# Autogenerated from man page /usr/share/man/man1/mtx-scite.1.gz
complete -c mtx-scite -l words --description 'convert spell-*. txt into spell-*. lua.'
complete -c mtx-scite -l tree --description 'converts a tree into an html tree (--source --target --numbers).'
complete -c mtx-scite -l file --description 'converts a file into an html tree (--source --target --numbers --lexer) AUTHO…'

