# mtx-package
# Autogenerated from man page /usr/share/man/man1/mtx-package.1.gz
complete -c mtx-package -l merge --description 'merge \'loadmodule\' into merge file AUTHOR More information about ConTeXt and …'

