# mtx-colors
# Autogenerated from man page /usr/share/man/man1/mtx-colors.1.gz
complete -c mtx-colors -l table --description 'show icc table AUTHOR More information about ConTeXt and the tools that come …'

