# mtx-timing
# Autogenerated from man page /usr/share/man/man1/mtx-timing.1.gz
complete -c mtx-timing -l xhtml --description 'make xhtml file.'
complete -c mtx-timing -l launch --description 'launch after conversion.'
complete -c mtx-timing -l remove --description 'remove after launching AUTHOR More information about ConTeXt and the tools th…'

