# mtx-watch
# Autogenerated from man page /usr/share/man/man1/mtx-watch.1.gz
complete -c mtx-watch -l logpath --description 'optional path for log files.'
complete -c mtx-watch -l watch --description 'watch given path [--delay].'
complete -c mtx-watch -l pipe --description 'use pipe instead of execute.'
complete -c mtx-watch -l delay --description 'delay between sweeps.'
complete -c mtx-watch -l automachine --description 'replace /machine/ in path /servername/.'
complete -c mtx-watch -l collect --description 'condense log files.'
complete -c mtx-watch -l cleanup --description 'remove files in given path [--force].'
complete -c mtx-watch -l showlog --description 'show log data AUTHOR More information about ConTeXt and the tools that come w…'

