# mtx-youless
# Autogenerated from man page /usr/share/man/man1/mtx-youless.1.gz
complete -c mtx-youless -l collect --description 'collect data from device.'
complete -c mtx-youless -l nobackup --description 'don\'t backup old datafile.'
complete -c mtx-youless -l nofile --description 'don\'t write data to file (for checking).'
complete -c mtx-youless -l kwh --description 'summative kwh data.'
complete -c mtx-youless -l watt --description 'collected watt data.'
complete -c mtx-youless -l host --description 'ip address of device AUTHOR More information about ConTeXt and the tools that…'

