# mtx-plain
# Autogenerated from man page /usr/share/man/man1/mtx-plain.1.gz
complete -c mtx-plain -l make --description 'create format file.'
complete -c mtx-plain -l fonts --description 'create plain font database.'
complete -c mtx-plain -l run --description 'process file.'
complete -c mtx-plain -l format --description 'format name (default: luatex-plain).'
complete -c mtx-plain -l engine --description 'engine to use (default: luatex).'
complete -c mtx-plain -l jit --description 'use luajittex AUTHOR More information about ConTeXt and the tools that come w…'

