# mtx-grep
# Autogenerated from man page /usr/share/man/man1/mtx-grep.1.gz
complete -c mtx-grep -l pattern --description 'search for pattern (optional).'
complete -c mtx-grep -l count --description 'count matches only.'
complete -c mtx-grep -l nocomment --description 'skip lines that start with %% or #.'
complete -c mtx-grep -l n --description 'show at most n matches.'
complete -c mtx-grep -l first --description 'only show first match.'
complete -c mtx-grep -l match --description 'return the match (if it is one).'
complete -c mtx-grep -l xml --description 'pattern is lpath expression AUTHOR More information about ConTeXt and the too…'

