# mtx-flac
# Autogenerated from man page /usr/share/man/man1/mtx-flac.1.gz
complete -c mtx-flac -l collect --description 'collect albums in xml file.'
complete -c mtx-flac -l pattern --description 'use pattern for locating files AUTHOR More information about ConTeXt and the …'

