# mtx-unicode
# Autogenerated from man page /usr/share/man/man1/mtx-unicode.1.gz
complete -c mtx-unicode -l whatever --description 'do whatever AUTHOR More information about ConTeXt and the tools that come wit…'

