# mupdf
# Autogenerated from man page /usr/share/man/man1/mupdf.1.gz
complete -c mupdf -s p --description 'Uses the given password to open an encrypted PDF file.'
complete -c mupdf -s r --description 'Changes the initial zoom level, specified as the resolution in dpi.'
complete -c mupdf -s A --description 'Changes the anti-aliasing quality, specified as a number of bits between 0 (o…'
complete -c mupdf -s C --description 'Sets the full-page tint using hexadecimal color syntax.'
complete -c mupdf -s W --description 'Page width in points for EPUB layout.'
complete -c mupdf -s H --description 'Page height in points for EPUB layout.'
complete -c mupdf -s S --description 'Font size in points for EPUB layout.'
complete -c mupdf -s U --description 'User style sheet for EPUB layout.'

