# netplan-generate
# Autogenerated from man page /usr/share/man/man8/netplan-generate.8.gz
complete -c netplan-generate -s h -l help --description 'Print basic help. RS . RE.'
complete -c netplan-generate -l debug --description 'Print debugging output during the process. RS . RE.'
complete -c netplan-generate -l root-dir --description 'Instead of looking in /{lib,etc,run}/netplan, look in /\\f[I]ROOT_DIR\\f[]/{lib…'
complete -c netplan-generate -l mapping --description 'Instead of generating output files, parse the configuration files and print s…'

