# netplan-apply
# Autogenerated from man page /usr/share/man/man8/netplan-apply.8.gz
complete -c netplan-apply -s h -l help --description 'Print basic help. RS . RE.'
complete -c netplan-apply -l debug --description 'Print debugging output during the process.  KNOWN ISSUES.'

