# netplan-try
# Autogenerated from man page /usr/share/man/man8/netplan-try.8.gz
complete -c netplan-try -s h -l help --description 'Print basic help. RS . RE.'
complete -c netplan-try -l debug --description 'Print debugging output during the process. RS . RE.'
complete -c netplan-try -l config-file --description 'In addition to the usual configuration, apply \\f[I]CONFIG_FILE\\f[].'
complete -c netplan-try -l timeout --description 'Wait for TIMEOUT seconds before reverting.  Defaults to 120 seconds.'

