# ninja
# Autogenerated from man page /usr/share/man/man1/ninja.1.gz
complete -c ninja -l version --description 'print ninja version ("1. 8. 2").'
complete -c ninja -s C --description 'change to DIR before doing anything else.'
complete -c ninja -s f --description 'specify input build file [default=build. ninja].'
complete -c ninja -s j --description 'run N jobs in parallel [default=derived from CPUs available].'
complete -c ninja -s k --description 'keep going until N jobs fail [default=1].'
complete -c ninja -s l --description 'do not start new jobs if the load average is greater than N.'
complete -c ninja -s n --description 'dry run (don\'t run commands but act like they succeeded).'
complete -c ninja -s v --description 'show all command lines while building.'
complete -c ninja -s d --description 'enable debugging (use -d list to list modes).'
complete -c ninja -s t --description 'run a subtool (use -t list to list subtools) P terminates toplevel options; f…'
complete -c ninja -s w --description 'adjust warnings (use -w list to list warnings) AUTHOR This manual page was wr…'

