# noise
# Autogenerated from man page /usr/share/man/man1/noise.1.gz
complete -c noise -l display --description 'X display to use.'
complete -c noise -s d -l debug --description 'Enable debug logging.'
complete -c noise -s h -l help --description 'Show help options.'
complete -c noise -l help-gtk --description 'Show GTK\\+ help options.'

