# numlockx
# Autogenerated from man page /usr/share/man/man1/numlockx.1.gz
complete -c numlockx -l help --description 'Display help AUTHOR This manual page was written by Chris Jones <chris@black-…'

