# ods2txt
# Autogenerated from man page /usr/share/man/man1/ods2txt.1.gz
complete -c ods2txt -l width --description 'Wrap text lines after WIDTH characters.'
complete -c ods2txt -l output --description 'Write output to FILE and not to standard output.'
complete -c ods2txt -l subst --description 'Select which non-ascii characters shall be replaced by ascii look-a-likes.'
complete -c ods2txt -l encoding --description 'Do not try to autodetect the terminal encoding, but convert the document to e…'
complete -c ods2txt -l raw --description 'Print raw XML.'
complete -c ods2txt -l version --description 'Show version and copyright information COPYRIGHT Copyright © 2006,2007 Dennis…'

