# odvitype
# Autogenerated from man page /usr/share/man/man1/odvitype.1.gz
complete -c odvitype -o dpi --description 'Set resolution to  REAL pixels per inch; default 300. 0. PP.'
complete -c odvitype -o magnification --description 'Override existing magnification with R NUMBER . PP.'
complete -c odvitype -o max-pages --description 'Process  NUMBER pages; default one million. PP.'
complete -c odvitype -o output-level --description 'Verbosity level, from 0 to 4; default 4. PP.'
complete -c odvitype -o page-start --description 'Start at R PAGE-SPEC , for example `2\' or `5. *. -2\'. PP.'
complete -c odvitype -o show-opcodes --description 'Show numeric opcodes (in decimal).'

