# odvicopy
# Autogenerated from man page /usr/share/man/man1/odvicopy.1.gz
complete -c odvicopy -o magnification --description 'Override existing magnification with R NUMBER . PP.'
complete -c odvicopy -o max-pages --description 'Process  NUMBER pages; default one million. PP.'
complete -c odvicopy -o page-start --description 'Start at PAGE-SPEC , for example `2\' or `5. *. -2\'.'

