# openjade
# Autogenerated from man page /usr/share/man/man1/openjade.1.gz
complete -c openjade -s d --description 'This specifies that dsssl_spec is the system identifier of the DSSSL specific…'
complete -c openjade -s G --description 'Debug mode.'
complete -c openjade -s c --description 'The filename arguments specify catalog files rather than the document entity.'
complete -c openjade -s s --description 'Strict compliance mode.'
complete -c openjade -s t --description 'output_type specifies the type of output as follows:.'
complete -c openjade -s o --description 'Write output to output_file instead of the default.'
complete -c openjade -s V --description 'This is equivalent to doing (define variable #t) except that this definition …'
complete -c openjade -o wtype --description 'Control warnings and errors.  Multiple -w options are allowed.'

