# ovf2ovp
# Autogenerated from man page /usr/share/man/man1/ovf2ovp.1.gz
complete -c ovf2ovp -o charcode-format --description 'output character codes according to type, either `hex\', `octal\' or `ascii\'.'
complete -c ovf2ovp -o char-format --description 'output character codes according to stype, either `num\' or `ascii\'.'
complete -c ovf2ovp -o num-format --description 'output numbers according to ntype, either `hex\' or `octal\'; default is hex.'
complete -c ovf2ovp -o text-format --description 'output coding scheme and family according to ttype, either `mixed\' or `upper\'…'
complete -c ovf2ovp -o help --description 'display a brief summary of syntax and options.'
complete -c ovf2ovp -o verbose --description 'display progress reports.'
complete -c ovf2ovp -o version --description 'output version information and exit.'

