# pandoc-citeproc
# Autogenerated from man page /usr/share/man/man1/pandoc-citeproc.1.gz
complete -c pandoc-citeproc -l 'bib2yaml\\f' --description 'Convert bibliography to YAML suitable for inclusion in pandoc metadata.'
complete -c pandoc-citeproc -l 'bib2json\\f' --description 'Convert bibliography to CSL JSON suitable for import into Zotero.'
complete -c pandoc-citeproc -l 'help\\f' --description 'Print usage information.'
complete -c pandoc-citeproc -l 'quiet\\f' --description 'Silence all warnings.'
complete -c pandoc-citeproc -l metadata-file --description 'Extension: yaml_metadata_block. ).'
complete -c pandoc-citeproc -s y -l bib2yaml --description 'Convert bibliography to YAML suitable for inclusion in pandoc metadata.'
complete -c pandoc-citeproc -s j -l bib2json --description 'Convert bibliography to CSL JSON suitable for import into Zotero.'
complete -c pandoc-citeproc -s f -l format --description 'Specify format of bibliography to be converted.'
complete -c pandoc-citeproc -s c -l columns --description 'Specify column to which to wrap YAML output produced using.'
complete -c pandoc-citeproc -s h -l help --description 'Print usage information.'
complete -c pandoc-citeproc -l man --description 'Print the man page in groff man format.'
complete -c pandoc-citeproc -l license --description 'Print the license.'
complete -c pandoc-citeproc -s q -l quiet --description 'Silence all warnings.'
complete -c pandoc-citeproc -s V -l version --description 'Print version.  NOTES General.'

