# pdfclose
# Autogenerated from man page /usr/share/man/man1/pdfclose.1.gz
complete -c pdfclose -s h -l help -s '?' --description 'output help and exit.'
complete -c pdfclose -s v -l version -s V --description 'output the version number and exit.'
complete -c pdfclose -s p -l page --description 'when starting the viewer, display page <n> of the document (notes: not all vi…'
complete -c pdfclose -s g -l goto --description 'when starting the viewer, display the page of the document containing the nam…'
complete -c pdfclose -s r -l reset_focus --description 'after sending commands to the PDF viewer, attempt to reset the input focus to…'
complete -c pdfclose -o viewer -l viewer --description 'use (respectively) Adobe Reader 9 (in a new window), Adobe Reader 9 (in a new…'

