# pdfjadetex
# Autogenerated from man page /usr/share/man/man1/pdfjadetex.1.gz
complete -c pdfjadetex -l fmt --description 'Use  format as the name of the format to be used, instead of the name by whic…'
complete -c pdfjadetex -l help --description 'Print help message and exit.'
complete -c pdfjadetex -l ini --description 'Be  pdfinitex , for dumping formats; this is implicitly true if the program i…'
complete -c pdfjadetex -l interaction --description 'Sets the interaction mode.'
complete -c pdfjadetex -l ipc --description 'Send DVI or PDF output to a socket as well as the usual output file.'
complete -c pdfjadetex -l ipc-start --description 'As  --ipc , and starts the server at the other end as well.'
complete -c pdfjadetex -l kpathsea-debug --description 'Sets path searching debugging flags according to the bitmask.'
complete -c pdfjadetex -l maketex --description 'Enable . RI mktex fmt , where  fmt must be one of  tex or R tfm .'
complete -c pdfjadetex -l no-maketex --description 'Disable . RI mktex fmt , where  fmt must be one of  tex or R tfm .'
complete -c pdfjadetex -l output-comment --description 'Use  string for the DVI file comment instead of the date.'
complete -c pdfjadetex -l progname --description 'Pretend to be program R name .'
complete -c pdfjadetex -l shell-escape --description 'Enable the  write18command construct.'
complete -c pdfjadetex -l version --description '.'

