# pedigree
# Autogenerated from man page /usr/share/man/man1/pedigree.1.gz
complete -c pedigree -s c --description 'The configuration file to read along with the system-wide and user\'s configur…'
complete -c pedigree -s d --description 'Debug mode on.'
complete -c pedigree -s o -o output_file --description 'The ouput file instead of input_file. tex.'
complete -c pedigree -s s -o start_id --description 'If this option is selected, the pedigree is constructed starting from the nod…'

