# pkfix-helper
# Autogenerated from man page /usr/share/man/man1/pkfix-helper.1.gz
complete -c pkfix-helper -s h -l help --description 'Display usage information and exit.'
complete -c pkfix-helper -s v -l verbose --description 'Increase the amount of status information that pkfix-helper displays as it ru…'
complete -c pkfix-helper -s f -l force --description 'Force pkfix-helper to associate a specific font with a given font name appear…'
complete -c pkfix-helper -s p -l ps --description 'Create a PostScript file called filename.'
complete -c pkfix-helper -s t -l tex --description 'Create a Plain TeX file called filename.'
complete -c pkfix-helper -s C -l cache --description 'Speed up \\s-1TFM\\s0 file processing by caching character metrics into file fi…'
complete -c pkfix-helper -s q -l quiet --description 'Instruct pkfix-helper to produce no output during its run except for fatal er…'
complete -c pkfix-helper -s 1 -l no-repeats --description 'Prevent pkfix-helper from associating the same fontspec with more than one dv…'
complete -c pkfix-helper -s i -l include --description 'Add fontspec to the list of font specifications against which pkfix-helper co…'
complete -c pkfix-helper -s x -l exclude --description 'Remove all font specifications matching regular expression regexp from pkfix-…'
complete -c pkfix-helper -s k -l keep --description 'Do not substitute a vector font for bitmapped font fontspec (\\f(CW\\*(C`Fa\\*(C…'
complete -c pkfix-helper -s a -l any-scale --description 'Allow any value to be used to scale a font when "\\f(CW\\*(C`*\\*(C\'" is specifi…'

