# pmxchords
# Autogenerated from man page /usr/share/man/man1/pmxchords.1.gz
complete -c pmxchords -s v --description 'output program name and version number, and quit.'
complete -c pmxchords -s h --description 'output usage summary and quit.'
complete -c pmxchords -s s --description 'stop after first step (of producing a temporary pmx file with transposed chor…'

