# prepmx
# Autogenerated from man page /usr/share/man/man1/prepmx.1.gz
complete -c prepmx -s b --description 'disable unbeamVocal.'
complete -c prepmx -s c --description 'disable doChords.'
complete -c prepmx -s D --description 'enable debugMode.'
complete -c prepmx -s f --description 'enable solfaNoteNames.'
complete -c prepmx -s i --description 'enable ignoreErrors.'
complete -c prepmx -s m --description 'disable doLyrics.'
complete -c prepmx -s n --description 'enable instrumentNames.'
complete -c prepmx -s t --description 'disable doUptext.'
complete -c prepmx -s u --description 'disable uptextOnRests.'
complete -c prepmx -s v --description 'enable beVerbose.'
complete -c prepmx -s w --description 'enable pedanticWarnings.'
complete -c prepmx -s H --description 'print enabled status of all options EXIT STATUS If no error was found, prepmx…'

