# prerex
# Autogenerated from man page /usr/share/man/man1/prerex.1.gz
complete -c prerex -s v --description 'output program name and version number, and quit.'
complete -c prerex -s h --description 'output usage summary and quit NOTES The main difference between  mini  and  t…'

