# purifyeps
# Autogenerated from man page /usr/share/man/man1/purifyeps.1.gz
complete -c purifyeps -l help --description 'Display \\*(L"Usage\\*(R" and \\*(L"Options\\*(R" from the purifyeps documentatio…'
complete -c purifyeps -s V -l version --description 'Display the purifyeps version number, copyright, and license.'
complete -c purifyeps -l fontmap --description 'Specify the name of a file that tells purifyeps how to map from TeX font name…'
complete -c purifyeps -l make-man -l section --description 'Automatically create a Unix man page for purifyeps.'

