# rdfind
# Autogenerated from man page /usr/share/man/man1/rdfind.1.gz
complete -c rdfind -o ignoreempty --description 'Ignore empty files.  (default).'
complete -c rdfind -o followsymlinks --description 'Follow symlinks.  Default is false.'
complete -c rdfind -o removeidentinode --description 'removes items found which have identical inode and device ID.'
complete -c rdfind -o checksum --description 'what type of checksum to be used: md5 or sha1.  Default is md5.'
complete -c rdfind -o makesymlinks --description 'Replace duplicate files with symbolic links.'
complete -c rdfind -o makehardlinks --description 'Replace duplicate files with hard links.'
complete -c rdfind -o makeresultsfile --description 'Make a results file results. txt (default) in the current directory.'
complete -c rdfind -o outputname --description 'Make the results file name to be "name" instead of the default results. txt.'
complete -c rdfind -o deleteduplicates --description 'Delete (unlink) files. PP  General options:.'
complete -c rdfind -o sleep --description 'sleeps X milliseconds between reading each file, to reduce load.'
complete -c rdfind -s n -o dryrun --description 'displays what should have been done, don\'t actually delete or link anything.'
complete -c rdfind -s h -o help -l help --description 'displays brief help message.'
complete -c rdfind -s v -o version -l version --description 'displays version number.  EXAMPLES.'

