# rzsh
# Autogenerated from man page /usr/share/man/man1/rzsh.1.gz
complete -c rzsh -s c --description 'Take the first argument as a command to execute, rather than reading commands…'
complete -c rzsh -s i --description 'Force shell to be interactive.'
complete -c rzsh -s s --description 'Force shell to read commands from the standard input.'
complete -c rzsh -s o --description '`-xo shwordsplit\' or `-xoshwordsplit\' is equivalent to `-x -o shwordsplit\'.'

