# sane-config
# Autogenerated from man page /usr/share/man/man1/sane-config.1.gz
complete -c sane-config -l version --description 'Print the currently installed version of libsane on the standard output.'
complete -c sane-config -l help --description 'Print a short usage message.  If OPTION is specified, help for that option (e.'
complete -c sane-config -l libs --description 'Print the additional libraries that are necessary to link a  SANE frontend to…'
complete -c sane-config -l ldflags --description 'Print the linker flags that are necessary to link a   SANE frontend to libsan…'
complete -c sane-config -l cflags --description 'Print the compiler flags that are necessary to compile a  SANE frontend.'
complete -c sane-config -l prefix --description 'Print the prefix used during compilation of libsane.'
complete -c sane-config -l exec-prefix --description 'Print the exec-prefix used during compilation of libsane.'

