# sbverify
# Autogenerated from man page /usr/share/man/man1/sbverify.1.gz
complete -c sbverify -l cert --description 'certificate (x509 certificate).'
complete -c sbverify -l no-verify --description 'don\'t perform certificate verification.'
complete -c sbverify -l detached --description 'read signature from <file>, instead of looking for an embedded signature.'

