# slingshot-launcher
# Autogenerated from man page /usr/share/man/man1/slingshot-launcher.1.gz
complete -c slingshot-launcher -s h -l help --description 'Show help message and exit.'
complete -c slingshot-launcher -s v -l version --description 'Print version info and exit.'
complete -c slingshot-launcher -s s -l silent --description 'Launch Slingshot as a background process without it appearing visually.'
complete -c slingshot-launcher -s c -l command-mode --description 'Not implemented yet.'
complete -c slingshot-launcher -l display --description 'X display to use AUTHOR Slingshot was written by Maxwell Barvian <maxwell@ele…'

