# snap-hmm
# Autogenerated from man page /usr/share/man/man1/snap-hmm.1.gz
complete -c snap-hmm -o help --description 'report useful information.'
complete -c snap-hmm -o lcmask --description 'treat lowercase as N.'
complete -c snap-hmm -o plus --description 'predict on plus strand only.'
complete -c snap-hmm -o minus --description 'predict on minus strand only.'
complete -c snap-hmm -o gff --description 'output annotation as GFF.'
complete -c snap-hmm -o ace --description 'output annotation as ACED.'
complete -c snap-hmm -o quiet --description 'do not send progress to STDERR.'
complete -c snap-hmm -o aa --description 'create FASTA file of proteins.'
complete -c snap-hmm -o tx --description 'create FASTA file of transcripts.'
complete -c snap-hmm -o xdef --description 'external definitions.'
complete -c snap-hmm -o name --description 'name for the gene [default snap].'

