# srcredact
# Autogenerated from man page /usr/share/man/man1/srcredact.1.gz
complete -c srcredact -s c --description 'Use the given pattern for comment lines to search for guards instead of the d…'
complete -c srcredact -s d --description 'Debug mode on.'
complete -c srcredact -s e --description 'Extract the contents for the current audience into the file file.'
complete -c srcredact -s h --description 'Print help information and exit.'
complete -c srcredact -s l --description 'List all audiences set in the file (one per line) and exit.'
complete -c srcredact -s u --description 'Take a edited file intended for the audience (the second non-option argument)…'
complete -c srcredact -s v --description 'Print version information and exit.'

