# t1lint
# Autogenerated from man page /usr/share/man/man1/t1lint.1.gz
complete -c t1lint -s q -l quiet --description 'Do not generate any error messages.   The only output will be the exit status.'
complete -c t1lint -s h -l help --description 'Print usage information and exit.  \' . Sp.'
complete -c t1lint -s v -l version --description 'Print the version number and some short non-warranty information and exit.'

