# t1reencode
# Autogenerated from man page /usr/share/man/man1/t1reencode.1.gz
complete -c t1reencode -l encoding -s e --description 'Read the encoding from R file , which must contain an encoding in .'
complete -c t1reencode -l encoding-text -s E --description 'Use the encoding in the  text argument, which must be formatted as a .'
complete -c t1reencode -l name -s n --description 'Set the output font\'s PostScript name to R name .'
complete -c t1reencode -l full-name -s N --description 'Set the output font\'s FullName to R name .'
complete -c t1reencode -l output -s o --description 'Send output to  file instead of standard output.  \' . Sp.'
complete -c t1reencode -l pfb -s b --description 'Output a PFB font.   This is the default.  \' . Sp.'
complete -c t1reencode -l pfa -s a --description 'Output a PFA font.  \' . Sp.'
complete -c t1reencode -s h -l help --description 'Print usage information and exit.  \' . Sp.'
complete -c t1reencode -l version --description 'Print the version number and some short non-warranty information and exit.'
complete -c t1reencode -s f --description 'option).   The new font will be called WarnockPro-RegularOsF.'

