# t1testpage
# Autogenerated from man page /usr/share/man/man1/t1testpage.1.gz
complete -c t1testpage -s g -l glyph --description 'Print only glyphs matching R glyphs .'
complete -c t1testpage -s s -l smoke --description 'Print smoke proofs, one glyph per page.   This option is preliminary.  \' . Sp.'
complete -c t1testpage -s o -l output --description 'Write the output proof to  file instead of the standard output.  \' . Sp.'
complete -c t1testpage -s h -l help --description 'Print usage information and exit.  \' . Sp.'
complete -c t1testpage -s v -l version --description 'Print the version number and some short non-warranty information and exit.'

