# texdirflatten
# Autogenerated from man page /usr/share/man/man1/texdirflatten.1.gz
complete -c texdirflatten -l file -s f --description 'Specifies input (La)TeX file.'
complete -c texdirflatten -l onetex -s 1 --description 'If specified, produces a single TeX file by expanding all input and include c…'
complete -c texdirflatten -l output -s o --description 'Directory to collect all files.'
complete -c texdirflatten -l imgexts --description 'Prepends to the prioritized list of image extensions to search when trying to…'
complete -c texdirflatten -l debug --description 'Enables copious amounts of debugging output - useful if something is going wr…'
complete -c texdirflatten -l version -s V --description 'Displays the current version number and the usage and exits.'

