# texdiff
# Autogenerated from man page /usr/share/man/man1/texdiff.1.gz
complete -c texdiff -l nofloats -s n --description 'If given, skips contents of figure environments, but does show insertions and…'

