# texexec
# Autogenerated from man page /usr/share/man/man1/texexec.1.gz
complete -c texexec -l make --description 'make formats.'
complete -c texexec -l check --description 'check versions.'
complete -c texexec -l process --description 'process file.'
complete -c texexec -l mptex --description 'process mp file.'
complete -c texexec -l mpxtex --description 'process mpx file.'
complete -c texexec -l mpgraphic --description 'process mp file to stand-alone graphics.'
complete -c texexec -l mpstatic --description 'process mp/ctx file to stand-alone graphics.'
complete -c texexec -l listing --description 'list of file content.'
complete -c texexec -l figures --description 'generate overview of figures.'
complete -c texexec -l modules --description 'generate module documentation.'
complete -c texexec -l pdfarrange --description 'impose pages (booklets).'
complete -c texexec -l pdfselect --description 'select pages from file(s).'
complete -c texexec -l pdfcopy --description 'copy pages from file(s).'
complete -c texexec -l pdftrim --description 'trim pages from file(s).'
complete -c texexec -l pdfcombine --description 'combine multiple pages.'
complete -c texexec -l pdfsplit --description 'split file in pages AUTHOR More information about ConTeXt and the tools that …'

