# texfot
# Autogenerated from man page /usr/share/man/man1/texfot.1.gz
complete -c texfot -l debug --description 'el.'
complete -c texfot -l no-debug --description 'el.'
complete -c texfot -l ignore --description 'el.'
complete -c texfot -l interactive --description 'el.'
complete -c texfot -l no-interactive --description 'el.'
complete -c texfot -l quiet --description 'el.'
complete -c texfot -l no-quiet --description 'el.'
complete -c texfot -l stderr --description 'el.'
complete -c texfot -l no-stderr --description 'el.'
complete -c texfot -l tee --description 'el.'
complete -c texfot -l version --description 'el.'
complete -c texfot -l help --description 'el.'

