# texhash
# Autogenerated from man page /usr/share/man/man1/texhash.1.gz
complete -c texhash -l help --description 'Print help message and exit.'
complete -c texhash -l version --description 'Print version information and exit.'

