# tie
# Autogenerated from man page /usr/share/man/man1/tie.1.gz
complete -c tie -s c --description 'Create a single change file from the given R changefile s.'
complete -c tie -s m --description 'Create a new master file by applying the given changefile s.'

