# tldr
# Autogenerated from man page /usr/share/man/man1/tldr.1.gz
complete -c tldr -s h -l help --description 'Show this help text.'
complete -c tldr -s v -l version --description 'Show version.'
complete -c tldr -l update --description 'Update tldr pages.'

