# tldr-hs
# Autogenerated from man page /usr/share/man/man1/tldr-hs.1.gz
complete -c tldr-hs -s h -l help --description 'Show this help text.'
complete -c tldr-hs -s v -l version --description 'Show version.'
complete -c tldr-hs -l update --description 'Update tldr pages.'

