# transmission-create
# Autogenerated from man page /usr/share/man/man1/transmission-create.1.gz
complete -c transmission-create -s h --description 'Show a short help page and exit.'
complete -c transmission-create -s o --description 'Save the generated . torrent to this filename.'
complete -c transmission-create -s p --description 'Flag the torrent as intended for use on private trackers.'
complete -c transmission-create -s c --description 'Add a comment to the torrent file.'
complete -c transmission-create -s s --description 'Set how many KiB each piece should be, overriding the preferred default.'
complete -c transmission-create -s t --description 'Add a tracker\'s announce URL to the . torrent.'

