# transmission-edit
# Autogenerated from man page /usr/share/man/man1/transmission-edit.1.gz
complete -c transmission-edit -s h --description 'Show a short help page and exit.'
complete -c transmission-edit -s a --description 'Add an announce URL to the torrent\'s announce-list if it\'s not already in the…'
complete -c transmission-edit -s d --description 'Remove an announce URL from the torrent\'s announce-list.'
complete -c transmission-edit -s r --description 'Substring search-and-replace inside a torrent\'s announce URLs.'

