# ttfdump
# Autogenerated from man page /usr/share/man/man1/ttfdump.1.gz
complete -c ttfdump -s h --description 'Print a help message on standard output and exit.'
complete -c ttfdump -s t --description 'If this option is specified then dump the table "tablename", otherwise  dump …'
complete -c ttfdump -s g --description 'If this option is specified then dump the glyph with index glyphnumber,  othe…'
complete -c ttfdump -s c --description 'Select a TrueType font in a TrueType Collection.'
complete -c ttfdump -s o --description 'Output of the dump.  If this option is not specified, dump to stdout.'
complete -c ttfdump -s i --description 'TrueType font file to be dumped.'

