# unsquashfs
# Autogenerated from man page /usr/share/man/man1/unsquashfs.1.gz
complete -c unsquashfs -s v -o version --description 'print version, licence and copyright information.'
complete -c unsquashfs -s d -o dest --description 'unsquash to PATHNAME, default "squashfs-root".'
complete -c unsquashfs -s n -o no-progress --description 'don\'t display the progress bar.'
complete -c unsquashfs -o no -o no-xattrs --description 'don\'t extract xattrs in file system.'
complete -c unsquashfs -s x -o xattrs --description 'extract xattrs in file system (default).'
complete -c unsquashfs -s p -o processors --description 'use NUMBER processors.  By default will use number of processors available.'
complete -c unsquashfs -s i -o info --description 'print files as they are unsquashed.'
complete -c unsquashfs -o li -o linfo --description 'print files as they are unsquashed with file attributes (like ls -l output).'
complete -c unsquashfs -s l -o ls --description 'list filesystem, but don\'t unsquash.'
complete -c unsquashfs -o ll -o lls --description 'list filesystem with file attributes (like ls -l output), but don\'t unsquash.'
complete -c unsquashfs -s f -o force --description 'if file already exists then overwrite.'
complete -c unsquashfs -s s -o stat --description 'display filesystem superblock information.'
complete -c unsquashfs -s e -o ef --description 'list of directories or files to extract.  One per line.'
complete -c unsquashfs -o da -o data-queue --description 'Set data queue to SIZE Mbytes.  Default 256 Mbytes.'
complete -c unsquashfs -o fr -o frag-queue --description 'Set fragment queue to SIZE Mbytes.  Default 256 Mbytes.'
complete -c unsquashfs -s r -o regex --description 'treat extract names as POSIX regular expressions rather than use the default …'

