# update-perl-sax-parsers
# Autogenerated from man page /usr/share/man/man8/update-perl-sax-parsers.8.gz
complete -c update-perl-sax-parsers -l add --description 'Adds the per-module info file for the indicated Perl SAX parser module to the…'
complete -c update-perl-sax-parsers -l remove --description 'Removes the per-module info file for Perl SAX parser module from the director…'
complete -c update-perl-sax-parsers -l update --description 'updates the overall Perl SAX parser modules info file R /etc/perl/XML/SAX/Par…'
complete -c update-perl-sax-parsers -l directory --description 'When used with  --add or with  --remove indicates the ParserDetails.'
complete -c update-perl-sax-parsers -l file --description 'Indicates the ParserDetails. ini file up be updated.'
complete -c update-perl-sax-parsers -l priority --description 'Specifies the priority of the SAX parser module to be added removed.'
complete -c update-perl-sax-parsers -l ucf --description 'Forcibly enable (X != 0) or disable (X = 0) of  ucf(1) .'
complete -c update-perl-sax-parsers -l quiet --description 'Prevents any diagnostic output.'
complete -c update-perl-sax-parsers -l test --description 'Prevents the modification of any files and enables debugging mode.'
complete -c update-perl-sax-parsers -l version --description 'Displays the version information and exits.'
complete -c update-perl-sax-parsers -l help --description 'Display the usage information and exits.'

