# update-language-dat
# Autogenerated from man page /usr/share/man/man8/update-language-dat.8.gz
complete -c update-language-dat -s c -l conf-file --description 'file giving additional hyphen specifications .'
complete -c update-language-dat -s d -l output-dir --description 'directory where files are written.'
complete -c update-language-dat -l checks --description 'perform sanity checks on the generated config file.'
complete -c update-language-dat -s q -l quiet --description 'don\'t write anything to the standard output during normal operation.'
complete -c update-language-dat -s h -s '?' -l help --description 'display this help message and exit.'
complete -c update-language-dat -s o -l output-file --description '.'
complete -c update-language-dat -l version --description 'output version information and exit FILES The default output directory is ,/v…'

