# update-updmap
# Autogenerated from man page /usr/share/man/man8/update-updmap.8.gz
complete -c update-updmap -l check --description 'Executes additional checks that all necessary files are present in the kpaths…'
complete -c update-updmap -l quiet --description 'don\'t write anything to the standard output during normal operation.'
complete -c update-updmap -l help --description 'print a summary of the command-line usage of update-updmap and exit.'
complete -c update-updmap -l version --description 'output version information and exit El Pp Note that the v option, which turns…'

