# update-tl-stacked-conffile
# Autogenerated from man page /usr/share/man/man8/update-tl-stacked-conffile.8.gz
complete -c update-tl-stacked-conffile -l check --description 'Executes additional checks that all necessary files are present in the kpaths…'
complete -c update-tl-stacked-conffile -l quiet --description 'don\'t write anything to the standard output during normal operation.'
complete -c update-tl-stacked-conffile -l help --description 'print a summary of the command-line usage of update-tl-stacked-conffile and e…'
complete -c update-tl-stacked-conffile -l version --description 'output version information and exit El Pp Note that the v option, which turns…'

