# update-fmtutil
# Autogenerated from man page /usr/share/man/man8/update-fmtutil.8.gz
complete -c update-fmtutil -l check --description 'Executes additional checks that all necessary files are present in the kpaths…'
complete -c update-fmtutil -l quiet --description 'don\'t write anything to the standard output during normal operation.'
complete -c update-fmtutil -l help --description 'print a summary of the command-line usage of update-fmtutil and exit.'
complete -c update-fmtutil -l version --description 'output version information and exit El Pp Note that the v option, which turns…'

