# update-language-lua
# Autogenerated from man page /usr/share/man/man8/update-language-lua.8.gz
complete -c update-language-lua -s c -l conf-file --description 'file giving additional hyphen specifications .'
complete -c update-language-lua -s d -l output-dir --description 'directory where files are written.'
complete -c update-language-lua -l checks --description 'perform sanity checks on the generated config file.'
complete -c update-language-lua -s q -l quiet --description 'don\'t write anything to the standard output during normal operation.'
complete -c update-language-lua -s h -s '?' -l help --description 'display this help message and exit.'
complete -c update-language-lua -s o -l output-file --description '.'
complete -c update-language-lua -l version --description 'output version information and exit FILES The default output directory is ,/v…'

