# vala-gen-introspect-0
# Autogenerated from man page /usr/share/man/man1/vala-gen-introspect-0.40.1.gz
complete -c vala-gen-introspect-0 -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c vala-gen-introspect-0 -s v -l verbose --description 'Be verbose.'
complete -c vala-gen-introspect-0 -s o -l output --description 'write output here instead of stdout.'
complete -c vala-gen-introspect-0 -s n -l namespace --description 'Namespace of the module, like \'Gtk\'.'
complete -c vala-gen-introspect-0 -l shared-library --description 'Shared library which contains the symbols.'
complete -c vala-gen-introspect-0 -l include-idl --description 'Other gidls to include.'

