# vala-gen-introspect
# Autogenerated from man page /usr/share/man/man1/vala-gen-introspect.1.gz
complete -c vala-gen-introspect -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c vala-gen-introspect -s v -l verbose --description 'Be verbose.'
complete -c vala-gen-introspect -s o -l output --description 'write output here instead of stdout.'
complete -c vala-gen-introspect -s n -l namespace --description 'Namespace of the module, like \'Gtk\'.'
complete -c vala-gen-introspect -l shared-library --description 'Shared library which contains the symbols.'
complete -c vala-gen-introspect -l include-idl --description 'Other gidls to include.'

