# vapigen
# Autogenerated from man page /usr/share/man/man1/vapigen.1.gz
complete -c vapigen -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c vapigen -l vapidir --description 'Look for package bindings in DIRECTORY.'
complete -c vapigen -l girdir --description 'Look for GIR bindings in DIRECTORY.'
complete -c vapigen -l metadatadir --description 'Look for GIR . metadata files in DIRECTORY.'
complete -c vapigen -l nostdpkg --description 'Do not include standard packages.'
complete -c vapigen -l pkg --description 'Include binding for PACKAGE.'
complete -c vapigen -l library --description 'Library name.'
complete -c vapigen -s d -l directory --description 'Output directory.'
complete -c vapigen -l disable-warnings --description 'Disable warnings.'
complete -c vapigen -l version --description 'Display version number.'
complete -c vapigen -s q -l quiet --description 'Do not print messages to the console.'

