# vapigen-0
# Autogenerated from man page /usr/share/man/man1/vapigen-0.40.1.gz
complete -c vapigen-0 -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c vapigen-0 -l vapidir --description 'Look for package bindings in DIRECTORY.'
complete -c vapigen-0 -l girdir --description 'Look for GIR bindings in DIRECTORY.'
complete -c vapigen-0 -l metadatadir --description 'Look for GIR . metadata files in DIRECTORY.'
complete -c vapigen-0 -l nostdpkg --description 'Do not include standard packages.'
complete -c vapigen-0 -l pkg --description 'Include binding for PACKAGE.'
complete -c vapigen-0 -l library --description 'Library name.'
complete -c vapigen-0 -s d -l directory --description 'Output directory.'
complete -c vapigen-0 -l disable-warnings --description 'Disable warnings.'
complete -c vapigen-0 -l version --description 'Display version number.'
complete -c vapigen-0 -s q -l quiet --description 'Do not print messages to the console.'

