# vlna
# Autogenerated from man page /usr/share/man/man1/vlna.1.gz
complete -c vlna -s f --description 'Filter.  The [filenames] are treated as follows: . RS.'
complete -c vlna -s s --description 'The silent mode.  No messages, warnings, statistics are printed.'
complete -c vlna -s r --description 'Do not create the backups.'
complete -c vlna -s v --description 'The set of characters treated as non-syllabic prepositions is declared by thi…'
complete -c vlna -s x --description 'The code is a string written in hexadecimal notation (even hexa digits is req…'
complete -c vlna -s m --description 'The math-modes ($. $ and $$. $$) are ignored.'
complete -c vlna -s n --description 'The verbatim mode (\\\\verb<char>. <char>, \\\\begtt.'
complete -c vlna -s l --description 'The LaTeX mode.'
complete -c vlna -s w --description 'The web mode (Knuth\'s web, no www:-).'

