# xbindkeys
# Autogenerated from man page /usr/share/man/man1/xbindkeys.1.gz
complete -c xbindkeys -s d -l defaults --description 'Print a default rc file.'
complete -c xbindkeys -s f -l file --description 'Use an alternative rc file.'
complete -c xbindkeys -s h -l help --description 'Short help on options plus version/author info.'
complete -c xbindkeys -s X -l display --description 'Set X display to use.'
complete -c xbindkeys -s v -l verbose --description 'More information on xbindkeys when it run.'
complete -c xbindkeys -s k -l key --description 'Identify one key pressed (useful to fill the configuration file).'
complete -c xbindkeys -o mk -l multikey --description 'Identify multi key pressed (useful to fill the configuration file).'
complete -c xbindkeys -s g -l geometry --description 'size and position of window with -k|-mk option.'
complete -c xbindkeys -s n -l nodaemon --description 'don\'t start as daemon If guile support have not been disabled:.'
complete -c xbindkeys -o dg -l defaults-guile --description 'Print a default guile configuration file.'
complete -c xbindkeys -o fg -l file-guile --description 'Use an alternative guile configuration file.'

