# xbindkeys_show
# Autogenerated from man page /usr/share/man/man1/xbindkeys_show.1.gz
complete -c xbindkeys_show -s f -l file --description 'Use an alternative rc file.'
complete -c xbindkeys_show -s h -l help --description 'Short help on options plus version/author info.'

