# zathura
# Autogenerated from man page /usr/share/man/man1/zathura.1.gz
complete -c zathura -s e -l reparent --description 'Reparents to window specified by xid.'
complete -c zathura -s c -l config-dir --description 'Path to the config directory.'
complete -c zathura -s d -l data-dir --description 'Path to the data directory.'
complete -c zathura -s p -l plugins-dir --description 'Path to the directory containing plugins.'
complete -c zathura -s w -l password --description 'The documents password.'
complete -c zathura -s P -l page --description 'Opens the document at the given page number.'
complete -c zathura -s l -l log-level --description 'Set log level (debug, info, warning, error).'
complete -c zathura -s x -l synctex-editor-command --description 'Set the synctex editor command.  Overrides the synctex-editor-command setting.'
complete -c zathura -l synctex-forward --description 'Jump to the given position.'
complete -c zathura -l synctex-pid --description 'Instead of looking for an instance having the correct file opened, try only t…'
complete -c zathura -l fork --description 'Fork into background.'
complete -c zathura -l version --description 'Display version string and exit.'
complete -c zathura -l help --description 'Display help and exit.'

