# zoe-loop
# Autogenerated from man page /usr/share/man/man1/zoe-loop.1.gz
complete -c zoe-loop -o all --description '.'
complete -c zoe-loop -o Vec -o IVec -o FVec -o TVec -o Hash -o Xtree --description '.'
complete -c zoe-loop -o Feature -o FeatureVec --description '.'
complete -c zoe-loop -o FastaFile -o DNA -o Protein -o Alignment -o CDS -o Palign --description '.'
complete -c zoe-loop -o Distribution -o Duration -o State -o Transition --description '.'
complete -c zoe-loop -o FeatureTable --description '.'
complete -c zoe-loop -o Model -o Scanner -o Counter --description '.'
complete -c zoe-loop -o HMM --description '.'

