.TH "wl_resource_iterator_context" 3 "Sat May 23 2020" "Version 1.18.90" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_resource_iterator_context
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "\fBwl_client_for_each_resource_iterator_func_t\fP \fBit\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBwl_client_for_each_resource_iterator_func_t\fP wl_resource_iterator_context::it"

.SS "void* wl_resource_iterator_context::user_data"


.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
