.TH "wl_shm_sigbus_data" 3 "Sat May 23 2020" "Version 1.18.90" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_shm_sigbus_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBwl_shm_pool\fP * \fBcurrent_pool\fP"
.br
.ti -1c
.RI "int \fBaccess_count\fP"
.br
.ti -1c
.RI "int \fBfallback_mapping_used\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int wl_shm_sigbus_data::access_count"

.SS "struct \fBwl_shm_pool\fP* wl_shm_sigbus_data::current_pool"

.SS "int wl_shm_sigbus_data::fallback_mapping_used"


.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
