.TH "wl_socket" 3 "Sat May 23 2020" "Version 1.18.90" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_socket
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBfd_lock\fP"
.br
.ti -1c
.RI "struct sockaddr_un \fBaddr\fP"
.br
.ti -1c
.RI "char \fBlock_addr\fP [\fBUNIX_PATH_MAX\fP+\fBLOCK_SUFFIXLEN\fP]"
.br
.ti -1c
.RI "struct \fBwl_list\fP \fBlink\fP"
.br
.ti -1c
.RI "struct \fBwl_event_source\fP * \fBsource\fP"
.br
.ti -1c
.RI "char * \fBdisplay_name\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct sockaddr_un wl_socket::addr"

.SS "char* wl_socket::display_name"

.SS "int wl_socket::fd"

.SS "int wl_socket::fd_lock"

.SS "struct \fBwl_list\fP wl_socket::link"

.SS "char wl_socket::lock_addr[\fBUNIX_PATH_MAX\fP+\fBLOCK_SUFFIXLEN\fP]"

.SS "struct \fBwl_event_source\fP* wl_socket::source"


.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
