code --install-extension bodil.file-browser
code --install-extension ecmel.vscode-html-css
code --install-extension golang.go
code --install-extension Ikuyadeu.r
code --install-extension jacobdufault.fuzzy-search
code --install-extension James-Yu.latex-workshop
code --install-extension kahole.magit
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension rust-lang.rust
code --install-extension tuttieee.emacs-mcx
code --install-extension vscodevim.vim
code --install-extension VSpaceCode.vspacecode
code --install-extension VSpaceCode.whichkey
code --install-extension zsh.go-snippets
